# Site settings
title:  APRIL
author: XU MING
alias: helloworld0000
username: helloworld0000
email: 167298@supinfo.com
description: Programmer,python,data mining.
url: "https://helloworld0000.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:title/
