# Site settings
title: decached.com â€” Akash Kothawale
author: Akash Kothawale
alias: decached
username: decached
email: io@decached.com
dp: https://s.gravatar.com/avatar/d7e35b17d3d8c8164e546648264fb88b?s=800
description: Terrible Poet, Musician, Comic Nerd, Engineer.
url: "http://decached.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:title/
